pipeline {
  agent any

  stages {
    stage("Demo") {
      steps {
        myFunc("Hello Jenkins")
        sh """
        
        """
      }
    }
  }
}

def myFunc(String myText) {
  echo "my tech ${myText}"
} 