pipeline {
  agent any
  parameters {
    choice(choices: ["TEST", "DEV", "QA", "PRE-PROD", "PROD"], description: "Enable service?", name: "myDevEnv")
  }
  stages {
    stage("Demo") {
      steps {
        echo "choice is set to: ${params.myDevEnv}"
      }
    }
  }
}