pipeline {
  agent any
  stages {
    stage("Demo") {
      steps {
        build job: "boolPipeline", 
          parameters: [[$class: "BooleanParameterValue", name: "myBoolean", value: true]]
      }
    }
  }
} 