pipeline {
  agent any

  environment {
    def myString = "Hello World"
    def myNumber = 10
    def myBool = false
  }

  stages {
    stage("DEMO") {
      steps {
        echo "myString: ${myString}"
        echo "myNumber: ${myNumber}"
        echo "myBool: ${myBool}"
      }
    }
  }
}